# Generated by Django 2.2.9 on 2020-02-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogTitle', models.CharField(max_length=120)),
                ('blogContent', models.TextField()),
                ('blogAuthor', models.CharField(max_length=120)),
            ],
        ),
    ]
